version: 2

project_name: redis-tabularis-plugin

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ././cmd/redis-tabularis-plugin
    binary: redis-tabularis-plugin

archives:
  - format: zip
    name_template: "redis-tabularis-plugin-{{ .Os }}-{{ .Arch }}"
    files:
      - manifest.json
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
